#!/usr/bin/env bash
tcpdump -i $1 -c 1 -eKnSt 'tcp[((tcp[12:1] & 0xf0) >> 2):4] = 0x47455420' 1>LOG
cat LOG | sed 's/ /\r\n/g' | cat -n > dump-results
index=$(grep -E 'BSSID:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}' dump-results | awk '{print $1}')
echo "You Index Value is $index"
